#server:
#  port: 8080
#  servlet:
#    context-path: /api
#
#spring:
#  application:
#    name: dormitory-management
#
#
#  # 本地数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dormitory_management?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
#      connection-timeout: 20000
#      idle-timeout: 300000
#      max-lifetime: 1200000
